hide_download: true
hide_download_original: null
leftnav:
- identifier: c5ddb732-d95d-9fa8-02d8-7587c7a53fc5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6632ed2b-3ebf-13bf-dae4-1e31ff6dd979
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: c98439d5-6a6d-7a4d-d7a4-d2681b1866d2
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 9cdff75d-72ec-17ec-65e8-d98104a1f627
  name: MATLAB Exercises
  pageRef: /pages/matlab-r-exercises
  weight: 40
- identifier: 39d5c010-34bb-c7d4-bd0c-427acf3354cd
  name: Problem Sets
  pageRef: /pages/problem-sets
  weight: 50
- identifier: 081d45ef-1888-e715-3d42-ce7eec113229
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: 627026af-f776-7e5c-9883-3022eddc34d9
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 70
